/*
 * Exact sound-bank path lists recovered from the matched executable table at
 * RVA 0x4D2320 and its 43 descriptors at RVA 0x4D3860. Array names retain
 * their matched virtual addresses so aliases and prefix subsets stay auditable.
 */

#include "jpb/sound_bank_data.h"

static char *sound_paths_1404d2320[43] = {
    "theed/bd_land.wav",
    "theed/flamed.wav",
    "theed/vhmhit.wav",
    "theed/tankstrt.wav",
    "theed/dstunfld.wav",
    "theed/grenade.wav",
    "theed/td_die.wav",
    "theed/riflfire.wav",
    "theed/vhmdie.wav",
    "theed/tankfire.wav",
    "theed/drdhit2.wav",
    "theed/vbdhit2.wav",
    "theed/barnlasr.wav",
    "theed/barnfal2.wav",
    "theed/jedigrab.wav",
    "theed/tanklasr.wav",
    "theed/vbdhit3.wav",
    "theed/td_fs1.wav",
    "theed/dstshld2.wav",
    "theed/hitnrun3.wav",
    "theed/dstshld1.wav",
    "theed/dstroll1.wav",
    "theed/td_legs.wav",
    "theed/tankstop.wav",
    "theed/drdhit1.wav",
    "theed/vbdhit1.wav",
    "theed/dstfold1.wav",
    "theed/dstfire1.wav",
    "theed/dstfall1.wav",
    "theed/td_lasr.wav",
    "theed/barnfal1.wav",
    "theed/tanksty1.wav",
    "theed/td_rvolv.wav",
    "theed/td_rotat.wav",
    "theed/jedithro.wav",
    "theed/lasrgate.wav",
    "theed/td_aim.wav",
    "theed/td_stand.wav",
    "theed/jawalasr.wav",
    "theed/vhmhelp2.wav",
    "theed/dstdie1.wav",
    "theed/vhmthax.wav",
    "theed/vhmhelp1.wav",
};

static char *sound_paths_1404d2480[40] = {
    "tato/trap.wav",
    "tato/jawa6.wav",
    "tato/wormlung.wav",
    "tato/tuskrifl.wav",
    "tato/rockroll.wav",
    "tato/clubhit.wav",
    "tato/jwdie.wav",
    "tato/dbdie2.wav",
    "tato/db_fs2.wav",
    "tato/dbhurt2.wav",
    "tato/tkhit2.wav",
    "tato/jwhit2.wav",
    "tato/thugblok.wav",
    "tato/dbroar2.wav",
    "tato/tkhit3.wav",
    "tato/jwhit1.wav",
    "tato/dbchomp.wav",
    "tato/tusken8.wav",
    "tato/db_fs1.wav",
    "tato/tkhit1.wav",
    "tato/vanhypen.wav",
    "tato/rockhit.wav",
    "tato/tusken5.wav",
    "tato/probehit.wav",
    "tato/dbroll.wav",
    "tato/dbtail.wav",
    "tato/probmove.wav",
    "tato/probfire.wav",
    "tato/tkatk.wav",
    "tato/jawalasr.wav",
    "tato/prob2fir.wav",
    "tato/vanhit2.wav",
    "tato/walbreak.wav",
    "tato/vanhit3.wav",
    "tato/jwatk.wav",
    "tato/tusken1.wav",
    "tato/prob2lop.wav",
    "tato/boldr01.wav",
    "tato/vanhit1.wav",
    "tato/vanhypey.wav",
};

static char *sound_paths_1404d25c0[33] = {
    "streets/bd_land.wav",
    "streets/vbdthere.wav",
    "streets/staphit.wav",
    "streets/flamed.wav",
    "streets/tankstrt.wav",
    "streets/dstunfld.wav",
    "streets/riflfire.wav",
    "streets/tankfire.wav",
    "streets/drdhit2.wav",
    "streets/vbdhit2.wav",
    "streets/dstkick.wav",
    "streets/barnlasr.wav",
    "streets/barnfal2.wav",
    "streets/tanklasr.wav",
    "streets/vbdhit3.wav",
    "streets/stapby3.wav",
    "streets/hitnrun3.wav",
    "streets/stapstdy.wav",
    "streets/dstroll1.wav",
    "streets/metlscrp.wav",
    "streets/tankstop.wav",
    "streets/drdhit1.wav",
    "streets/vbdhit1.wav",
    "streets/dstfold1.wav",
    "streets/dstfire1.wav",
    "streets/dstfall1.wav",
    "streets/plasma.wav",
    "streets/barnfal1.wav",
    "streets/tanksty1.wav",
    "streets/stapfire.wav",
    "streets/vbdgetdm.wav",
    "streets/leafthru.wav",
    "streets/dstdie1.wav",
};

static char *sound_paths_1404d26d0[14] = {
    "ruins/gungstaf.wav",
    "ruins/nuna.wav",
    "ruins/vbnend.wav",
    "ruins/vggdie.wav",
    "ruins/nunabite.wav",
    "ruins/riflfire.wav",
    "ruins/drdhit2.wav",
    "ruins/barnlasr.wav",
    "ruins/barnfal2.wav",
    "ruins/thugblok.wav",
    "ruins/smlfalls.wav",
    "ruins/splash.wav",
    "ruins/ambswamp.wav",
    "ruins/plantatk.wav",
};

static char *sound_paths_1404d2740[41] = {
    "resident/sabrhit7.wav",
    "resident/sabrsw06.wav",
    "resident/xjedscrl.wav",
    "resident/xlocklvl.wav",
    "resident/sabrhit5.wav",
    "resident/sabrsw05.wav",
    "resident/explomed.wav",
    "resident/jediskid.wav",
    "resident/xjump4.wav",
    "resident/xlvselct.wav",
    "resident/xrespawn.wav",
    "resident/rico4.wav",
    "resident/sabrhit4.wav",
    "resident/sabrsw04.wav",
    "resident/sabrsw03.wav",
    "resident/rico2.wav",
    "resident/sabrsw02.wav",
    "resident/xlvbrows.wav",
    "resident/bodyfal2.wav",
    "resident/xjump3.wav",
    "resident/rico1.wav",
    "resident/sabrhit1.wav",
    "resident/sabrsw01.wav",
    "resident/bodyfal1.wav",
    "resident/pullup.wav",
    "resident/xpoison.wav",
    "resident/xlockon.wav",
    "resident/pnchswng.wav",
    "resident/xsecret.wav",
    "resident/xjedsel.wav",
    "resident/jedihit.wav",
    "resident/xjedland.wav",
    "resident/explosm.wav",
    "resident/jediroll.wav",
    "resident/xopt_sel.wav",
    "resident/xsavload.wav",
    "resident/tink.wav",
    "resident/lshum.wav",
    "resident/xsaberup.wav",
    "resident/xpointbp.wav",
    "resident/ricoext.wav",
};

static char *sound_paths_1404d2890[12] = {
    "qui_gon/vjdie.wav",
    "qui_gon/vbjhit.wav",
    "qui_gon/vmjhit.wav",
    "qui_gon/vsjhit.wav",
    "qui_gon/pulsgrnd.wav",
    "qui_gon/vjatk2.wav",
    "qui_gon/vjatk3.wav",
    "qui_gon/areajedi.wav",
    "qui_gon/pushjedi.wav",
    "qui_gon/vjatk1.wav",
    "qui_gon/tfrcheal.wav",
    "qui_gon/vthisway.wav",
};

static char *sound_paths_1404d28f0[12] = {
    "plo/vjdie.wav",
    "plo/vbjhit.wav",
    "plo/vmjhit.wav",
    "plo/vsjhit.wav",
    "plo/trflsphr.wav",
    "plo/vjatk2.wav",
    "plo/vjatk1.wav",
    "plo/stmfrcht.wav",
    "plo/rdrvsh.wav",
    "plo/tdrvsh.wav",
    "plo/rcrckdth.wav",
    "plo/vthisway.wav",
};

static char *sound_paths_1404d2950[8] = {
    "panaka/vjdie.wav",
    "panaka/vbjhit.wav",
    "panaka/vmjhit.wav",
    "panaka/vsjhit.wav",
    "panaka/thugkick.wav",
    "panaka/amidlasr.wav",
    "panaka/thugstab.wav",
    "panaka/prob2fir.wav",
};

static char *sound_paths_1404d2990[37] = {
    "palace/bd_land.wav",
    "palace/vbdthere.wav",
    "palace/staphit.wav",
    "palace/vhmhit.wav",
    "palace/dstunfld.wav",
    "palace/vhmdie.wav",
    "palace/drdhit2.wav",
    "palace/vbdhit2.wav",
    "palace/dstkick.wav",
    "palace/barnlasr.wav",
    "palace/barnfal2.wav",
    "palace/jedigrab.wav",
    "palace/vbdhit3.wav",
    "palace/stapby3.wav",
    "palace/dstshld2.wav",
    "palace/stapstdy.wav",
    "palace/dstshld1.wav",
    "palace/dstroll1.wav",
    "palace/drdhit1.wav",
    "palace/vbdhit1.wav",
    "palace/dstfold1.wav",
    "palace/dstfire1.wav",
    "palace/dstfall1.wav",
    "palace/plasma.wav",
    "palace/barnfal1.wav",
    "palace/drsldsm.wav",
    "palace/jedithro.wav",
    "palace/stapfire.wav",
    "palace/vbdgetdm.wav",
    "palace/vqnhit2.wav",
    "palace/vhmhelp2.wav",
    "palace/vqnhit3.wav",
    "palace/dstdie1.wav",
    "palace/glasbrk1.wav",
    "palace/vhmthax.wav",
    "palace/vqnhit1.wav",
    "palace/vhmhelp1.wav",
};

static char *sound_paths_1404d2ac0[10] = {
    "obi_wan/vjdie.wav",
    "obi_wan/vbjhit.wav",
    "obi_wan/vmjhit.wav",
    "obi_wan/vsjhit.wav",
    "obi_wan/trflsphr.wav",
    "obi_wan/vjatk2.wav",
    "obi_wan/pushjedi.wav",
    "obi_wan/vjatk1.wav",
    "obi_wan/tfastsbr.wav",
    "obi_wan/vthisway.wav",
};

static char *sound_paths_1404d2b10[58] = {
    "mini4/trap.wav",
    "mini4/vt1hit2.wav",
    "mini4/vt3hit2.wav",
    "mini4/vt2hit2.wav",
    "mini4/bd_land.wav",
    "mini4/vbdthere.wav",
    "mini4/vt1hit1.wav",
    "mini4/staphit.wav",
    "mini4/vt3hit1.wav",
    "mini4/vt2hit1.wav",
    "mini4/flamed.wav",
    "mini4/tuskrifl.wav",
    "mini4/dstunfld.wav",
    "mini4/thughit.wav",
    "mini4/thugbeam.wav",
    "mini4/riflfire.wav",
    "mini4/drdhit2.wav",
    "mini4/vbdhit2.wav",
    "mini4/dstkick.wav",
    "mini4/barnlasr.wav",
    "mini4/barnfal2.wav",
    "mini4/jedigrab.wav",
    "mini4/tkhit2.wav",
    "mini4/vbdhit3.wav",
    "mini4/thugkick.wav",
    "mini4/thugblok.wav",
    "mini4/stapby3.wav",
    "mini4/tkhit3.wav",
    "mini4/stapstdy.wav",
    "mini4/dstroll1.wav",
    "mini4/drdhit1.wav",
    "mini4/vbdhit1.wav",
    "mini4/dstfold1.wav",
    "mini4/dstfire1.wav",
    "mini4/dstfall1.wav",
    "mini4/tusken8.wav",
    "mini4/plasma.wav",
    "mini4/barnfal1.wav",
    "mini4/tkhit1.wav",
    "mini4/vpkhit1.wav",
    "mini4/drsldsm.wav",
    "mini4/thugswng.wav",
    "mini4/jedithro.wav",
    "mini4/thugshld.wav",
    "mini4/stapfire.wav",
    "mini4/tusken5.wav",
    "mini4/vbdgetdm.wav",
    "mini4/tkatk.wav",
    "mini4/vt1atk.wav",
    "mini4/vt2atk.wav",
    "mini4/vt3atk.wav",
    "mini4/thuglasr.wav",
    "mini4/thugstab.wav",
    "mini4/vpkatk.wav",
    "mini4/dstdie1.wav",
    "mini4/tusken1.wav",
    "mini4/glasbrk1.wav",
    "mini4/xtimerbp.wav",
};

static char *sound_paths_1404d2ce0[9] = {
    "mini3/vjjdie.wav",
    "mini3/vjjargh2.wav",
    "mini3/vjjhit2.wav",
    "mini3/vjjargh3.wav",
    "mini3/vjjhit3.wav",
    "mini3/vjjstop.wav",
    "mini3/vjjargh1.wav",
    "mini3/vjjhit1.wav",
    "mini3/xtimerbp.wav",
};

static char *sound_paths_1404d2d30[32] = {
    "mini2/nuna.wav",
    "mini2/vbdthere.wav",
    "mini2/flamed.wav",
    "mini2/dstunfld.wav",
    "mini2/nunabite.wav",
    "mini2/vjjdie.wav",
    "mini2/drdhit2.wav",
    "mini2/vbdhit2.wav",
    "mini2/vjjargh2.wav",
    "mini2/barnlasr.wav",
    "mini2/barnfal2.wav",
    "mini2/jedigrab.wav",
    "mini2/vjjhit2.wav",
    "mini2/vbdhit3.wav",
    "mini2/vjjargh3.wav",
    "mini2/ambswamp.wav",
    "mini2/vjjhit3.wav",
    "mini2/vjjstop.wav",
    "mini2/drdhit1.wav",
    "mini2/vbdhit1.wav",
    "mini2/vjjargh1.wav",
    "mini2/plasma.wav",
    "mini2/barnfal1.wav",
    "mini2/vjjhit1.wav",
    "mini2/jedithro.wav",
    "mini2/telem01l.wav",
    "mini2/ambpond.wav",
    "mini2/vbdgetdm.wav",
    "mini2/mttstdy.wav",
    "mini2/spores01.wav",
    "mini2/xtimerbp.wav",
    "mini2/peko.wav",
};

static char *sound_paths_1404d2e30[15] = {
    "mini1/vbdhit2.wav",
    "mini1/vpthelp2.wav",
    "mini1/vbdhit3.wav",
    "mini1/vpthit2.wav",
    "mini1/vpthit1.wav",
    "mini1/vbdhit1.wav",
    "mini1/vpthelp1.wav",
    "mini1/drsldsm.wav",
    "mini1/stapfire.wav",
    "mini1/amidlasr.wav",
    "mini1/thugstab.wav",
    "mini1/prob2fir.wav",
    "mini1/glasbrk1.wav",
    "mini1/xtimerbp.wav",
    "mini1/vptthax.wav",
};

static char *sound_paths_1404d2eb0[39] = {
    "maul/vmlpause.wav",
    "maul/vbjhit.wav",
    "maul/vmjhit.wav",
    "maul/vsjhit.wav",
    "maul/vmldie.wav",
    "maul/sbrswdb1.wav",
    "maul/trflsphr.wav",
    "maul/sbrswdb3.wav",
    "maul/areajedi.wav",
    "maul/sbrswdb2.wav",
    "maul/vmlatk2.wav",
    "maul/vmlatk3.wav",
    "maul/rcrckdth.wav",
    "maul/vmlatk1.wav",
    "marsh/nuna.wav",
    "marsh/wormlung.wav",
    "marsh/vbdthere.wav",
    "marsh/wormhurt.wav",
    "marsh/wormspit.wav",
    "marsh/flamed.wav",
    "marsh/dstunfld.wav",
    "marsh/nunabite.wav",
    "marsh/vjjdie.wav",
    "marsh/drdhit2.wav",
    "marsh/vbdhit2.wav",
    "marsh/vjjargh2.wav",
    "marsh/wormwlk2.wav",
    "marsh/barnlasr.wav",
    "marsh/barnfal2.wav",
    "marsh/jedigrab.wav",
    "marsh/vjjhit2.wav",
    "marsh/vbdhit3.wav",
    "marsh/vjjargh3.wav",
    "marsh/ambswamp.wav",
    "marsh/vjjhit3.wav",
    "marsh/drdhit1.wav",
    "marsh/vbdhit1.wav",
    "marsh/vjjargh1.wav",
    "marsh/wormwlk1.wav",
};

static char *sound_paths_1404d2f20[39] = {
    "marsh/nuna.wav",
    "marsh/wormlung.wav",
    "marsh/vbdthere.wav",
    "marsh/wormhurt.wav",
    "marsh/wormspit.wav",
    "marsh/flamed.wav",
    "marsh/dstunfld.wav",
    "marsh/nunabite.wav",
    "marsh/vjjdie.wav",
    "marsh/drdhit2.wav",
    "marsh/vbdhit2.wav",
    "marsh/vjjargh2.wav",
    "marsh/wormwlk2.wav",
    "marsh/barnlasr.wav",
    "marsh/barnfal2.wav",
    "marsh/jedigrab.wav",
    "marsh/vjjhit2.wav",
    "marsh/vbdhit3.wav",
    "marsh/vjjargh3.wav",
    "marsh/ambswamp.wav",
    "marsh/vjjhit3.wav",
    "marsh/drdhit1.wav",
    "marsh/vbdhit1.wav",
    "marsh/vjjargh1.wav",
    "marsh/wormwlk1.wav",
    "marsh/plasma.wav",
    "marsh/barnfal1.wav",
    "marsh/vjjhit1.wav",
    "marsh/jedithro.wav",
    "marsh/vjjfolo.wav",
    "marsh/telem01l.wav",
    "marsh/wormdie.wav",
    "marsh/ambpond.wav",
    "marsh/vbdgetdm.wav",
    "marsh/wormscrm.wav",
    "marsh/wormslam.wav",
    "marsh/roaches.wav",
    "marsh/spores01.wav",
    "marsh/peko.wav",
};

static char *sound_paths_1404d3060[12] = {
    "mace/sbrthrw.wav",
    "mace/vjdie.wav",
    "mace/vbjhit.wav",
    "mace/vmjhit.wav",
    "mace/vsjhit.wav",
    "mace/vjatk2.wav",
    "mace/sbrswdb3.wav",
    "mace/vjatk1.wav",
    "mace/tsbrtwrl.wav",
    "mace/sbrtwrl.wav",
    "mace/tf_absrb.wav",
    "mace/vthisway.wav",
};

static char *sound_paths_1404d30c0[34] = {
    "hangar/windclif.wav",
    "hangar/trap.wav",
    "hangar/bd_land.wav",
    "hangar/staphit.wav",
    "hangar/flamed.wav",
    "hangar/dstunfld.wav",
    "hangar/riflfire.wav",
    "hangar/drdhit2.wav",
    "hangar/vbdhit2.wav",
    "hangar/dstkick.wav",
    "hangar/barnlasr.wav",
    "hangar/barnfal2.wav",
    "hangar/jedigrab.wav",
    "hangar/vpthelp2.wav",
    "hangar/vbdhit3.wav",
    "hangar/vpthit2.wav",
    "hangar/smlfalls.wav",
    "hangar/stapby3.wav",
    "hangar/vpthit1.wav",
    "hangar/stapstdy.wav",
    "hangar/dstroll1.wav",
    "hangar/drdhit1.wav",
    "hangar/vbdhit1.wav",
    "hangar/dstfold1.wav",
    "hangar/dstfire1.wav",
    "hangar/dstfall1.wav",
    "hangar/barnfal1.wav",
    "hangar/vpthelp1.wav",
    "hangar/drsldsm.wav",
    "hangar/jedithro.wav",
    "hangar/stapfire.wav",
    "hangar/dstdie1.wav",
    "hangar/xtimerbp.wav",
    "hangar/vptthax.wav",
};

static char *sound_paths_1404d31d0[8] = {
    "gungan_2/gungstaf.wav",
    "gungan_2/vggdie.wav",
    "gungan_2/vgghalt.wav",
    "gungan_2/vggtaunt.wav",
    "gungan_2/vgghit2.wav",
    "gungan_2/vggatk2.wav",
    "gungan_2/vgghit1.wav",
    "gungan_2/vggatk1.wav",
};

static char *sound_paths_1404d3210[8] = {
    "gungan_1/gungstaf.wav",
    "gungan_1/vggdie.wav",
    "gungan_1/vgghalt.wav",
    "gungan_1/vggtaunt.wav",
    "gungan_1/vgghit2.wav",
    "gungan_1/vggatk2.wav",
    "gungan_1/vgghit1.wav",
    "gungan_1/vggatk1.wav",
};

static char *sound_paths_1404d3250[40] = {
    "fed/dfgetht.wav",
    "fed/dfdie.wav",
    "fed/bd_land.wav",
    "fed/vbdthere.wav",
    "fed/conveyl.wav",
    "fed/dstunfld.wav",
    "fed/drdhit2.wav",
    "fed/vbdhit2.wav",
    "fed/dstkick.wav",
    "fed/dfhvr2.wav",
    "fed/dfpsby1.wav",
    "fed/lgspark.wav",
    "fed/smspark.wav",
    "fed/dr_fed1.wav",
    "fed/barnlasr.wav",
    "fed/barnfal2.wav",
    "fed/vbdhit3.wav",
    "fed/break2.wav",
    "fed/ld_clap.wav",
    "fed/elev1lp.wav",
    "fed/dfrblstr.wav",
    "fed/dstroll1.wav",
    "fed/break1.wav",
    "fed/drdhit1.wav",
    "fed/vbdhit1.wav",
    "fed/dstfold1.wav",
    "fed/dstfire1.wav",
    "fed/dstfall1.wav",
    "fed/barnfal1.wav",
    "fed/elev1beg.wav",
    "fed/ld_roll.wav",
    "fed/dftrnsfm.wav",
    "fed/ld_movmt.wav",
    "fed/vbdgetdm.wav",
    "fed/pisthit.wav",
    "fed/ld_rotat.wav",
    "fed/ld_spin.wav",
    "fed/walbreak.wav",
    "fed/dstdie1.wav",
    "fed/pistloop.wav",
};

static char *sound_paths_1404d3390[11] = {
    "destroyu/dstunfld.wav",
    "destroyu/drdhit2.wav",
    "destroyu/dstkick.wav",
    "destroyu/dstshld2.wav",
    "destroyu/dstshld1.wav",
    "destroyu/dstroll1.wav",
    "destroyu/drdhit1.wav",
    "destroyu/dstfold1.wav",
    "destroyu/dstfire1.wav",
    "destroyu/dstfall1.wav",
    "destroyu/dstdie1.wav",
};

static char *sound_paths_1404d33f0[11] = {
    "destroye/dstunfld.wav",
    "destroye/drdhit2.wav",
    "destroye/dstkick.wav",
    "destroye/dstshld2.wav",
    "destroye/dstshld1.wav",
    "destroye/dstroll1.wav",
    "destroye/drdhit1.wav",
    "destroye/dstfold1.wav",
    "destroye/dstfire1.wav",
    "destroye/dstfall1.wav",
    "destroye/dstdie1.wav",
};

static char *sound_paths_1404d3450[18] = {
    "council/vydmaul.wav",
    "council/vydtempt.wav",
    "council/vydchose.wav",
    "council/vydlrnhe.wav",
    "council/vydjpb.wav",
    "council/vydjar.wav",
    "council/vydshedo.wav",
    "council/vydplo.wav",
    "council/vydqueen.wav",
    "council/vydtnkhm.wav",
    "council/vydgood.wav",
    "council/vydmace.wav",
    "council/vydwise.wav",
    "council/vydbet2.wav",
    "council/vydpoor.wav",
    "council/vydqui.wav",
    "council/vydobi.wav",
    "council/vydadi.wav",
};

static char *sound_paths_1404d34e0[48] = {
    "corus1/vt4hit3.wav",
    "corus1/taxiariv.wav",
    "corus1/vt4hit2.wav",
    "corus1/vt4atk2.wav",
    "corus1/vt1hit2.wav",
    "corus1/vt3hit2.wav",
    "corus1/vt2hit2.wav",
    "corus1/telebust.wav",
    "corus1/vt4hit1.wav",
    "corus1/vt4atk1.wav",
    "corus1/vt4die.wav",
    "corus1/vt1hit1.wav",
    "corus1/vt3hit1.wav",
    "corus1/vt2hit1.wav",
    "corus1/thughit.wav",
    "corus1/vt2taunt.wav",
    "corus1/ventshft.wav",
    "corus1/thugbeam.wav",
    "corus1/teleprt2.wav",
    "corus1/vt4tant2.wav",
    "corus1/thugkick.wav",
    "corus1/thugblok.wav",
    "corus1/elev1lp.wav",
    "corus1/vt4tant1.wav",
    "corus1/taxiloop.wav",
    "corus1/teleprt1.wav",
    "corus1/vpkhit1.wav",
    "corus1/elev1beg.wav",
    "corus1/thugswng.wav",
    "corus1/fanblow.wav",
    "corus1/thugshld.wav",
    "corus1/probehit.wav",
    "corus1/vt3taunt.wav",
    "corus1/vt1taunt.wav",
    "corus1/elev1end.wav",
    "corus1/peck.wav",
    "corus1/probmove.wav",
    "corus1/probfire.wav",
    "corus1/vt1atk.wav",
    "corus1/vt2atk.wav",
    "corus1/vt3atk.wav",
    "corus1/thuglasr.wav",
    "corus1/thugstab.wav",
    "corus1/vpkatk.wav",
    "corus1/prob2fir.wav",
    "corus1/passby1.wav",
    "corus1/prob2lop.wav",
    "corus1/taxiaway.wav",
};

static char *sound_paths_1404d3660[39] = {
    "core/beam_on.wav",
    "core/bd_land.wav",
    "core/vmlpause.wav",
    "core/bluebeam.wav",
    "core/windlite.wav",
    "core/vmldie.wav",
    "core/riflfire.wav",
    "core/drdhit2.wav",
    "core/vbdhit2.wav",
    "core/forcfld2.wav",
    "core/lgspark.wav",
    "core/sbrswdb1.wav",
    "core/trflsphr.wav",
    "core/barnlasr.wav",
    "core/barnfal2.wav",
    "core/vbdhit3.wav",
    "core/splash.wav",
    "core/elev1lp.wav",
    "core/sbrswdb3.wav",
    "core/drdhit1.wav",
    "core/vbdhit1.wav",
    "core/dstfire1.wav",
    "core/dstfall1.wav",
    "core/areajedi.wav",
    "core/forcfld1.wav",
    "core/sbrswdb2.wav",
    "core/barnfal1.wav",
    "core/elev1beg.wav",
    "core/drsldsm.wav",
    "core/beam_off.wav",
    "core/fan_big.wav",
    "core/lasrgate.wav",
    "core/vmlhit2.wav",
    "core/vmlatk2.wav",
    "core/vmlatk3.wav",
    "core/rcrckdth.wav",
    "core/frcfld01.wav",
    "core/vmlhit1.wav",
    "core/vmlatk1.wav",
};

static char *sound_paths_1404d3798[7] = {
    "amidala/vjdie.wav",
    "amidala/vbjhit.wav",
    "amidala/vmjhit.wav",
    "amidala/vsjhit.wav",
    "amidala/thugkick.wav",
    "amidala/amidlasr.wav",
    "amidala/thugstab.wav",
};

static char *sound_paths_1404d37d0[11] = {
    "adi/vjdie.wav",
    "adi/vbjhit.wav",
    "adi/vmjhit.wav",
    "adi/vsjhit.wav",
    "adi/f_clk1.wav",
    "adi/vjatk2.wav",
    "adi/areajedi.wav",
    "adi/vjatk1.wav",
    "adi/msmrz.wav",
    "adi/vthisway.wav",
    "adi/wowjedi1.wav",
};

static char *sound_paths_1404d3828[7] = {
    "tato/probmove.wav",
    "tato/probfire.wav",
    "theed/barnlasr.wav",
    "theed/barnfal2.wav",
    "theed/barnfal1.wav",
    "mini1/vbdhit2.wav",
    "mini4/xtimerbp.wav",
};

tAudioSFX_Bank audioSFX_aSFXBanks[AUDIO_SFX_BANK_COUNT] = {
    {"resident/", sound_paths_1404d2740, 41},
    {"marsh/", sound_paths_1404d2f20, 39},
    {"theed/", sound_paths_1404d2320, 43},
    {"tato/", sound_paths_1404d2480, 40},
    {"streets/", sound_paths_1404d25c0, 33},
    {"ruins/", sound_paths_1404d26d0, 14},
    {"palace/", sound_paths_1404d2990, 37},
    {"mini4/", sound_paths_1404d2b10, 58},
    {"mini3/", sound_paths_1404d2ce0, 9},
    {"mini2/", sound_paths_1404d2d30, 32},
    {"mini1/", sound_paths_1404d2e30, 15},
    {"hangar/", sound_paths_1404d30c0, 34},
    {"fed/", sound_paths_1404d3250, 40},
    {"council/", sound_paths_1404d3450, 18},
    {"corus1/", sound_paths_1404d34e0, 48},
    {"core/", sound_paths_1404d3660, 39},
    {"qui_gon/", sound_paths_1404d2890, 12},
    {"plo/", sound_paths_1404d28f0, 12},
    {"panaka/", sound_paths_1404d2950, 8},
    {"obi_wan/", sound_paths_1404d2ac0, 10},
    {"maul/", sound_paths_1404d2eb0, 14},
    {"mace/", sound_paths_1404d3060, 12},
    {"gungan_2/", sound_paths_1404d31d0, 8},
    {"gungan_1/", sound_paths_1404d3210, 8},
    {"destroyu/", sound_paths_1404d3390, 11},
    {"destroye/", sound_paths_1404d33f0, 11},
    {"amidala/", sound_paths_1404d3798, 7},
    {"adi/", sound_paths_1404d37d0, 11},
    {"battle_d/", sound_paths_1404d3250, 40},
    {"flame/", sound_paths_1404d2320, 43},
    {"ki_adi/", sound_paths_1404d2890, 12},
    {"loader/", sound_paths_1404d3250, 40},
    {"maul_p/", sound_paths_1404d2eb0, 39},
    {"pilot/", sound_paths_1404d2eb0, 39},
    {"rifle/", sound_paths_1404d3250, 40},
    {"thug_1/", sound_paths_1404d2320, 43},
    {"thug_2", sound_paths_1404d34e0, 48},
    {"thug_3", sound_paths_1404d34e0, 48},
    {"thug_4", sound_paths_1404d34e0, 48},
    {"turret_d/", sound_paths_1404d34e0, 48},
    {"tusken_r/", sound_paths_1404d2320, 43},
    {"tusken_s/", sound_paths_1404d2480, 40},
    {"training_level/", sound_paths_1404d3828, 7},
};
