/*
 * Exact initialized PDB global theCredits (type 0x77D2), recovered
 * from matched game.exe RVA 0x4C8ED0. The leading byte 1 marks a
 * heading; empty entries retain the original vertical spacing.
 * Generated by tools/extract_credit_data.py.
 */

#include "jpb/menu.h"

unsigned char *theCredits[JPB_CREDIT_LINE_COUNT] = {
    (unsigned char *)"\001LucasArts", /*   0 */
    (unsigned char *)"", /*   1 */
    (unsigned char *)"\001Project Leader/Programmer", /*   2 */
    (unsigned char *)"Robert Blackadder", /*   3 */
    (unsigned char *)"", /*   4 */
    (unsigned char *)"\001Project Leader/Lead Artist", /*   5 */
    (unsigned char *)"Kevin Boyle", /*   6 */
    (unsigned char *)"", /*   7 */
    (unsigned char *)"\001Programming", /*   8 */
    (unsigned char *)"Charlie Skilbeck - Lead", /*   9 */
    (unsigned char *)"Patrick Costello - Technology", /*  10 */
    (unsigned char *)"Ife Olowe-Interface, Audio", /*  11 */
    (unsigned char *)"Jon Menzies-World Rendering", /*  12 */
    (unsigned char *)"", /*  13 */
    (unsigned char *)"\001 3D Animators/Artists", /*  14 */
    (unsigned char *)"Armando Lluch", /*  15 */
    (unsigned char *)"Aron Hatfield", /*  16 */
    (unsigned char *)"Chris Schultz", /*  17 */
    (unsigned char *)"Christina Boyle", /*  18 */
    (unsigned char *)"David Weinstein", /*  19 */
    (unsigned char *)"Razmig Mavlian", /*  20 */
    (unsigned char *)"Yu Hon Ng", /*  21 */
    (unsigned char *)"", /*  22 */
    (unsigned char *)"\001 3D Modelers/Artists ", /*  23 */
    (unsigned char *)"Bernard Eral", /*  24 */
    (unsigned char *)"Bill Hennes", /*  25 */
    (unsigned char *)"Mai Nguyen", /*  26 */
    (unsigned char *)"Paul Davies", /*  27 */
    (unsigned char *)"Tim Tao", /*  28 */
    (unsigned char *)"", /*  29 */
    (unsigned char *)"\001Level Designer/AI Scripting", /*  30 */
    (unsigned char *)"Derek Flippo", /*  31 */
    (unsigned char *)"June Park", /*  32 */
    (unsigned char *)"", /*  33 */
    (unsigned char *)"\001World Artist", /*  34 */
    (unsigned char *)"Bill Hennes", /*  35 */
    (unsigned char *)"Carl Wattenberg", /*  36 */
    (unsigned char *)"Martin Yee", /*  37 */
    (unsigned char *)"Michael Licht", /*  38 */
    (unsigned char *)"Rebecca Perez", /*  39 */
    (unsigned char *)"Ti- Ning Kwa", /*  40 */
    (unsigned char *)"", /*  41 */
    (unsigned char *)"\001Texture Artist", /*  42 */
    (unsigned char *)"Ashot Melkumov", /*  43 */
    (unsigned char *)"Lissa Klanor - Interface", /*  44 */
    (unsigned char *)"Marcia Thomas", /*  45 */
    (unsigned char *)"", /*  46 */
    (unsigned char *)"\001Cutscene Models", /*  47 */
    (unsigned char *)"Lea Mai Nguyen", /*  48 */
    (unsigned char *)"", /*  49 */
    (unsigned char *)"\001Additional Cutscene Models", /*  50 */
    (unsigned char *)"Arnaud Mayet", /*  51 */
    (unsigned char *)"Chris Weakley", /*  52 */
    (unsigned char *)"Matt Intrieri", /*  53 */
    (unsigned char *)"", /*  54 */
    (unsigned char *)"\001Effects Artists", /*  55 */
    (unsigned char *)"Jeffrey Kember", /*  56 */
    (unsigned char *)"Clint Young", /*  57 */
    (unsigned char *)"Mike Terpstra", /*  58 */
    (unsigned char *)"", /*  59 */
    (unsigned char *)"\001Tech", /*  60 */
    (unsigned char *)"June Park", /*  61 */
    (unsigned char *)"", /*  62 */
    (unsigned char *)"\001Tools Programming", /*  63 */
    (unsigned char *)"Glen Volk", /*  64 */
    (unsigned char *)"", /*  65 */
    (unsigned char *)"\001Conceptual Artists", /*  66 */
    (unsigned char *)"Cory Allemeier", /*  67 */
    (unsigned char *)"Eddie Del Rio", /*  68 */
    (unsigned char *)"", /*  69 */
    (unsigned char *)"\001Lead Tester/Gameplay Consultant", /*  70 */
    (unsigned char *)"Alex Neuse", /*  71 */
    (unsigned char *)"", /*  72 */
    (unsigned char *)"\001Assistant Lead Tester/ Gameplay Consultant", /*  73 */
    (unsigned char *)"Chuck McFadden", /*  74 */
    (unsigned char *)"Andy Alamano", /*  75 */
    (unsigned char *)"", /*  76 */
    (unsigned char *)"\001Testers/ Gameplay Consultants", /*  77 */
    (unsigned char *)"Brent Jay Andaya Jalipa II", /*  78 */
    (unsigned char *)"Bryan Erck", /*  79 */
    (unsigned char *)"Chane \"Doc\" Hollander", /*  80 */
    (unsigned char *)"Joseph John Talavera II", /*  81 */
    (unsigned char *)"Shang-Ju Chen", /*  82 */
    (unsigned char *)"David Felton", /*  83 */
    (unsigned char *)"Max Roghi", /*  84 */
    (unsigned char *)"Roger Romero", /*  85 */
    (unsigned char *)"Peter Lim", /*  86 */
    (unsigned char *)"", /*  87 */
    (unsigned char *)"\001International Testers", /*  88 */
    (unsigned char *)"Erik Ellicock - Lead", /*  89 */
    (unsigned char *)"", /*  90 */
    (unsigned char *)"\001Production Manager", /*  91 */
    (unsigned char *)"Reeve S Thompson", /*  92 */
    (unsigned char *)"Camela B Martin", /*  93 */
    (unsigned char *)"", /*  94 */
    (unsigned char *)"\001Production Coordinator", /*  95 */
    (unsigned char *)"Amy Tiller", /*  96 */
    (unsigned char *)"Rachel M Hardwick", /*  97 */
    (unsigned char *)"", /*  98 */
    (unsigned char *)"\001Script Supervisor", /*  99 */
    (unsigned char *)"Haden Blackman", /* 100 */
    (unsigned char *)"", /* 101 */
    (unsigned char *)"\001Render Solutions/Technical Assistant", /* 102 */
    (unsigned char *)"Yasmin Khan", /* 103 */
    (unsigned char *)"", /* 104 */
    (unsigned char *)"\001Voice Department Manager", /* 105 */
    (unsigned char *)"Tamlynn Niglio", /* 106 */
    (unsigned char *)"", /* 107 */
    (unsigned char *)"\001Voice Producer/Director", /* 108 */
    (unsigned char *)"Darragh O'Farrell", /* 109 */
    (unsigned char *)"", /* 110 */
    (unsigned char *)"\001Voice Editors", /* 111 */
    (unsigned char *)"Will Beckman", /* 112 */
    (unsigned char *)"Coya Elliott", /* 113 */
    (unsigned char *)"Cindy Wong", /* 114 */
    (unsigned char *)"", /* 115 */
    (unsigned char *)"\001Voice Processing", /* 116 */
    (unsigned char *)"Michael Frayne", /* 117 */
    (unsigned char *)"Julian Kwasneski", /* 118 */
    (unsigned char *)"", /* 119 */
    (unsigned char *)"\001Voice Production Supervisor", /* 120 */
    (unsigned char *)"Peggy Bartlett", /* 121 */
    (unsigned char *)"", /* 122 */
    (unsigned char *)"\001Voice Cast", /* 123 */
    (unsigned char *)"Anakin Skywalker: Jake Lloyd", /* 124 */
    (unsigned char *)"Qui-Gon Jinn: James Warwick", /* 125 */
    (unsigned char *)"Obi-Wan Kenobi: Scott Cleverdon", /* 126 */
    (unsigned char *)"Jar Jar: Ahmed Best", /* 127 */
    (unsigned char *)"Queen Amidala: Grey Delisle", /* 128 */
    (unsigned char *)"Adi Gallia: Nancy Giles", /* 129 */
    (unsigned char *)"Boss Nass: Greg Burson", /* 130 */
    (unsigned char *)"Ki-Adi-Mundi: Jess Harnell", /* 131 */
    (unsigned char *)"Mace Windu: Kevin Michael Richardson", /* 132 */
    (unsigned char *)"Plo Koon: Gregg Berger", /* 133 */
    (unsigned char *)"Yoda: Tom Kane", /* 134 */
    (unsigned char *)"Battle Droid: Jess Harnell", /* 135 */
    (unsigned char *)"Commander Droid: Tom Kane", /* 136 */
    (unsigned char *)"Darth Maul: Gregg Berger", /* 137 */
    (unsigned char *)"Drop Ship Security System: Peter Vilkin", /* 138 */
    (unsigned char *)"Goliath Droid: Greg Berger", /* 139 */
    (unsigned char *)"Gungan Guard 1: Kevin Michael Richardson", /* 140 */
    (unsigned char *)"Gungan Guard 2: Tom Kane", /* 141 */
    (unsigned char *)"Gungan Security Chief: David Jeremiah", /* 142 */
    (unsigned char *)"Handmaiden: Grey Delisle", /* 143 */
    (unsigned char *)"Jawa: Peter Vilkin", /* 144 */
    (unsigned char *)"Peck: Greg Burson", /* 145 */
    (unsigned char *)"Pedestrian Male: David Jeremiah", /* 146 */
    (unsigned char *)"Male Pilot: Peter Vilkin", /* 147 */
    (unsigned char *)"TC-14 Protocol Droid: Grey Delisle", /* 148 */
    (unsigned char *)"Thug 1: Tom Kane", /* 149 */
    (unsigned char *)"Thug 2: Greg Berger", /* 150 */
    (unsigned char *)"Thug 3: Scott Cleverdon", /* 151 */
    (unsigned char *)"Thug 4: Kevin Michael Richardson", /* 152 */
    (unsigned char *)"Tusken Raider: David Jeremiah", /* 153 */
    (unsigned char *)"", /* 154 */
    (unsigned char *)"\001Voices recorded at", /* 155 */
    (unsigned char *)"ScreenMusic Studios", /* 156 */
    (unsigned char *)"Studio City California", /* 157 */
    (unsigned char *)"LucasArts Entertainment", /* 158 */
    (unsigned char *)"Company LLC", /* 159 */
    (unsigned char *)"San Rafael California", /* 160 */
    (unsigned char *)"", /* 161 */
    (unsigned char *)"\001Music Composed and Conducted by", /* 162 */
    (unsigned char *)"Star Wars music composed by John Williams.", /* 163 */
    (unsigned char *)"(c) Warner-Tamerlane Publishing Corp.", /* 164 */
    (unsigned char *)"& Bantha Music.", /* 165 */
    (unsigned char *)"\001All rights administered by", /* 166 */
    (unsigned char *)"Warner-Tamerlane Publishing Corp.", /* 167 */
    (unsigned char *)"All rights reserved. Used by permission.", /* 168 */
    (unsigned char *)"", /* 169 */
    (unsigned char *)"\001Lead Sound Designer/Music Editing", /* 170 */
    (unsigned char *)"\001Coruscant Thug Boss Music by", /* 171 */
    (unsigned char *)"Clint Bajakian", /* 172 */
    (unsigned char *)"", /* 173 */
    (unsigned char *)"\001Sound Design", /* 174 */
    (unsigned char *)"Larry The O", /* 175 */
    (unsigned char *)"Jeff Kliment", /* 176 */
    (unsigned char *)"Dave Levison", /* 177 */
    (unsigned char *)"", /* 178 */
    (unsigned char *)"\001Sound Assistant", /* 179 */
    (unsigned char *)"Michael Frayne", /* 180 */
    (unsigned char *)"", /* 181 */
    (unsigned char *)"\001Sound Department Manager", /* 182 */
    (unsigned char *)"Michael Land", /* 183 */
    (unsigned char *)"", /* 184 */
    (unsigned char *)"\001Sound Department Coordinator", /* 185 */
    (unsigned char *)"Malena Slettom", /* 186 */
    (unsigned char *)"", /* 187 */
    (unsigned char *)"\001Original Star Wars Sound Effects", /* 188 */
    (unsigned char *)"Ben Burtt", /* 189 */
    (unsigned char *)"", /* 190 */
    (unsigned char *)"\001International Tools and Development Manager:", /* 191 */
    (unsigned char *)"Andre Bremmer", /* 192 */
    (unsigned char *)"", /* 193 */
    (unsigned char *)"\001Associate Localization Manager", /* 194 */
    (unsigned char *)"Jennifer Bencal", /* 195 */
    (unsigned char *)"", /* 196 */
    (unsigned char *)"\001International Production Coordinator:", /* 197 */
    (unsigned char *)"Ben Becker", /* 198 */
    (unsigned char *)"", /* 199 */
    (unsigned char *)"\001Product Marketing Manager", /* 200 */
    (unsigned char *)"Joel Dreskin", /* 201 */
    (unsigned char *)"", /* 202 */
    (unsigned char *)"\001Public Relations", /* 203 */
    (unsigned char *)"Tom Sarris", /* 204 */
    (unsigned char *)"Josh Moore", /* 205 */
    (unsigned char *)"Thea Crosby-Levine", /* 206 */
    (unsigned char *)"", /* 207 */
    (unsigned char *)"\001Marketing Coordinator", /* 208 */
    (unsigned char *)"Anne Barson", /* 209 */
    (unsigned char *)"", /* 210 */
    (unsigned char *)"\001Internet Marketing Specialist", /* 211 */
    (unsigned char *)"Jim Passalacqua", /* 212 */
    (unsigned char *)"", /* 213 */
    (unsigned char *)"\001International Marketing Manager", /* 214 */
    (unsigned char *)"Simon Etchells", /* 215 */
    (unsigned char *)"", /* 216 */
    (unsigned char *)"\001International Marketing Coordinator", /* 217 */
    (unsigned char *)"Kathy Apostoli", /* 218 */
    (unsigned char *)"", /* 219 */
    (unsigned char *)"\001Manual Writer", /* 220 */
    (unsigned char *)"Geoffrey Keighley", /* 221 */
    (unsigned char *)"", /* 222 */
    (unsigned char *)"\001Manual Editor", /* 223 */
    (unsigned char *)"Mollie Boero", /* 224 */
    (unsigned char *)"", /* 225 */
    (unsigned char *)"\001Manual Designer", /* 226 */
    (unsigned char *)"Chris Epting", /* 227 */
    (unsigned char *)"", /* 228 */
    (unsigned char *)"\001Package Design", /* 229 */
    (unsigned char *)"B.D. Fox and Friends", /* 230 */
    (unsigned char *)"", /* 231 */
    (unsigned char *)"\001Package Illustrator", /* 232 */
    (unsigned char *)"Robh Ruppel", /* 233 */
    (unsigned char *)"", /* 234 */
    (unsigned char *)"\001Product Support Manager", /* 235 */
    (unsigned char *)"Paul Purdy", /* 236 */
    (unsigned char *)"", /* 237 */
    (unsigned char *)"\001Hint Line Supervisor", /* 238 */
    (unsigned char *)"Tabitha Tosti", /* 239 */
    (unsigned char *)"", /* 240 */
    (unsigned char *)"\001Senior Hint Line Representative", /* 241 */
    (unsigned char *)"Bob McGehee", /* 242 */
    (unsigned char *)"", /* 243 */
    (unsigned char *)"\001Quality Assurance Manager", /* 244 */
    (unsigned char *)"Dan Pettit", /* 245 */
    (unsigned char *)"", /* 246 */
    (unsigned char *)"\001President", /* 247 */
    (unsigned char *)"Simon Jeffery", /* 248 */
    (unsigned char *)"", /* 249 */
    (unsigned char *)"\001Vice President of Global Sales and Marketing", /* 250 */
    (unsigned char *)"Mary Bihr", /* 251 */
    (unsigned char *)"", /* 252 */
    (unsigned char *)"\001Director of Art", /* 253 */
    (unsigned char *)"Karen Chelini", /* 254 */
    (unsigned char *)"", /* 255 */
    (unsigned char *)"\001Director of Production Services", /* 256 */
    (unsigned char *)"Camela B Martin", /* 257 */
    (unsigned char *)"", /* 258 */
    (unsigned char *)"\001Director of Technology", /* 259 */
    (unsigned char *)"Malcolm Johnson", /* 260 */
    (unsigned char *)"", /* 261 */
    (unsigned char *)"\001Controller", /* 262 */
    (unsigned char *)"Tom McCarthy", /* 263 */
    (unsigned char *)"", /* 264 */
    (unsigned char *)"\001Thanks to the Following LucasArts Departments", /* 265 */
    (unsigned char *)"Art Administration", /* 266 */
    (unsigned char *)"Business Affairs", /* 267 */
    (unsigned char *)"Deathstar Shipping Services", /* 268 */
    (unsigned char *)"Facilities", /* 269 */
    (unsigned char *)"Finance", /* 270 */
    (unsigned char *)"Human Resources", /* 271 */
    (unsigned char *)"Information Services", /* 272 */
    (unsigned char *)"Product Support", /* 273 */
    (unsigned char *)"", /* 274 */
    (unsigned char *)"\001Archivists", /* 275 */
    (unsigned char *)"Wendy Kaplan", /* 276 */
    (unsigned char *)"Kellie Walker", /* 277 */
    (unsigned char *)"", /* 278 */
    (unsigned char *)"\001Lucas Licensing", /* 279 */
    (unsigned char *)"Howard Roffman", /* 280 */
    (unsigned char *)"Stacey Mollema", /* 281 */
    (unsigned char *)"Chris Gollaher", /* 282 */
    (unsigned char *)"", /* 283 */
    (unsigned char *)"\001Thanks to Industrial Light and Magic", /* 284 */
    (unsigned char *)"Andy Hendrickson", /* 285 */
    (unsigned char *)"Ken Beyer", /* 286 */
    (unsigned char *)"Jeff King", /* 287 */
    (unsigned char *)"Nancy Luckoff", /* 288 */
    (unsigned char *)"", /* 289 */
    (unsigned char *)"\001Thanks to Softimage", /* 290 */
    (unsigned char *)"Sylvia Hunt", /* 291 */
    (unsigned char *)"", /* 292 */
    (unsigned char *)"\001Sega Europe", /* 293 */
    (unsigned char *)"Mark Maslowicz", /* 294 */
    (unsigned char *)"Chris Fougler", /* 295 */
    (unsigned char *)"Adam Rabin", /* 296 */
    (unsigned char *)"", /* 297 */
    (unsigned char *)"\001Thanks To", /* 298 */
    (unsigned char *)"Jack Sorensen", /* 299 */
    (unsigned char *)"Steve Dauterman", /* 300 */
    (unsigned char *)"Nick Pavis", /* 301 */
    (unsigned char *)"Chris Miles", /* 302 */
    (unsigned char *)"Kellie Tauzin", /* 303 */
    (unsigned char *)"Linda Grisanti", /* 304 */
    (unsigned char *)"Mike Stemmle", /* 305 */
    (unsigned char *)"Sean Clark", /* 306 */
    (unsigned char *)"Tony Hsieh", /* 307 */
    (unsigned char *)"Big Ape", /* 308 */
    (unsigned char *)"", /* 309 */
    (unsigned char *)"\001Personal Thanks", /* 310 */
    (unsigned char *)"Belkys Barbara Perez", /* 311 */
    (unsigned char *)"Stephen Mack", /* 312 */
    (unsigned char *)"Marianna Lebedeff", /* 313 */
    (unsigned char *)"Nelson Ng", /* 314 */
    (unsigned char *)"Byron Viles", /* 315 */
    (unsigned char *)"Peter & Terrie Kember", /* 316 */
    (unsigned char *)"Tracy Dean, Jenn, & Julia Blackadder", /* 317 */
    (unsigned char *)"Orlando Lluch", /* 318 */
    (unsigned char *)"Jhina , Tina and the monkey girls", /* 319 */
    (unsigned char *)"Angel", /* 320 */
    (unsigned char *)"Zimbo the Magnificent", /* 321 */
    (unsigned char *)"Karla Moran", /* 322 */
    (unsigned char *)"Diane Caliva", /* 323 */
    (unsigned char *)"Chris \"Fergus\" Gray", /* 324 */
    (unsigned char *)"Giovanna Velez", /* 325 */
    (unsigned char *)"Winnie Jong", /* 326 */
    (unsigned char *)"Drew Willis", /* 327 */
    (unsigned char *)"Liam, Jake, and Aaron", /* 328 */
    (unsigned char *)"Mike Blair", /* 329 */
    (unsigned char *)"Kate Warne", /* 330 */
    (unsigned char *)"Stromboli", /* 331 */
    (unsigned char *)"", /* 332 */
    (unsigned char *)"\001Aspyr", /* 333 */
    (unsigned char *)"", /* 334 */
    (unsigned char *)"\001Co - CEO", /* 335 */
    (unsigned char *)"Michael Rogers", /* 336 */
    (unsigned char *)"Ted Staloch", /* 337 */
    (unsigned char *)"", /* 338 */
    (unsigned char *)"\001VP of Operations", /* 339 */
    (unsigned char *)"Ryan Anson", /* 340 */
    (unsigned char *)"", /* 341 */
    (unsigned char *)"\001VP of Finance & Accounting", /* 342 */
    (unsigned char *)"Anabel Balderas", /* 343 */
    (unsigned char *)"", /* 344 */
    (unsigned char *)"\001Development", /* 345 */
    (unsigned char *)"", /* 346 */
    (unsigned char *)"\001Manager, Production", /* 347 */
    (unsigned char *)"David Ballard", /* 348 */
    (unsigned char *)"", /* 349 */
    (unsigned char *)"\001Senior Producers", /* 350 */
    (unsigned char *)"Marc Sherman", /* 351 */
    (unsigned char *)"Brian Glazebrook", /* 352 */
    (unsigned char *)"Robert Cooper", /* 353 */
    (unsigned char *)"", /* 354 */
    (unsigned char *)"\001Producers", /* 355 */
    (unsigned char *)"Jonathan Woo", /* 356 */
    (unsigned char *)"Jacky Coiro", /* 357 */
    (unsigned char *)"", /* 358 */
    (unsigned char *)"\001Associate II Producers", /* 359 */
    (unsigned char *)"Moye Daniel", /* 360 */
    (unsigned char *)"Amalh Mendelsohn", /* 361 */
    (unsigned char *)"Heather Corson", /* 362 */
    (unsigned char *)"", /* 363 */
    (unsigned char *)"\001Associate I Producer", /* 364 */
    (unsigned char *)"Benjamin Smith", /* 365 */
    (unsigned char *)"", /* 366 */
    (unsigned char *)"\001Associate II Data Quality Analyst", /* 367 */
    (unsigned char *)"Ryan Stocks", /* 368 */
    (unsigned char *)"", /* 369 */
    (unsigned char *)"\001Principle Software Engineer", /* 370 */
    (unsigned char *)"Tim McDaniel", /* 371 */
    (unsigned char *)"", /* 372 */
    (unsigned char *)"\001Art Director", /* 373 */
    (unsigned char *)"Bren King", /* 374 */
    (unsigned char *)"", /* 375 */
    (unsigned char *)"\001 3D Artists", /* 376 */
    (unsigned char *)"Stephen Colahan", /* 377 */
    (unsigned char *)"Lorenzo Giotti", /* 378 */
    (unsigned char *)"Karley Karensky", /* 379 */
    (unsigned char *)"Lorena Barran Gervaz", /* 380 */
    (unsigned char *)"Ryan Reed", /* 381 */
    (unsigned char *)"", /* 382 */
    (unsigned char *)"\001Programming Director", /* 383 */
    (unsigned char *)"Alex Hollander", /* 384 */
    (unsigned char *)"", /* 385 */
    (unsigned char *)"\001Senior Manager, Engineering", /* 386 */
    (unsigned char *)"Scott Phillips", /* 387 */
    (unsigned char *)"", /* 388 */
    (unsigned char *)"\001Manager, Engineering", /* 389 */
    (unsigned char *)"Stephen Hughes", /* 390 */
    (unsigned char *)"Ayo Orimoloye", /* 391 */
    (unsigned char *)"", /* 392 */
    (unsigned char *)"\001Lead Software Engineer", /* 393 */
    (unsigned char *)"Ken Cobb", /* 394 */
    (unsigned char *)"", /* 395 */
    (unsigned char *)"\001Senior Software Engineers", /* 396 */
    (unsigned char *)"Alan Condevillamar", /* 397 */
    (unsigned char *)"Andy Molloy", /* 398 */
    (unsigned char *)"Tim Powell", /* 399 */
    (unsigned char *)"", /* 400 */
    (unsigned char *)"\001Senior Infrastructure Engineer", /* 401 */
    (unsigned char *)"Steven Cattrell", /* 402 */
    (unsigned char *)"", /* 403 */
    (unsigned char *)"\001Software Engineers", /* 404 */
    (unsigned char *)"Luke Alexander", /* 405 */
    (unsigned char *)"Wyatt Johnson", /* 406 */
    (unsigned char *)"Matt Mikuta", /* 407 */
    (unsigned char *)"Luke Soldano", /* 408 */
    (unsigned char *)"Bobby Thurman", /* 409 */
    (unsigned char *)"Zachary Varnadore", /* 410 */
    (unsigned char *)"Justin Baldwin", /* 411 */
    (unsigned char *)"Connor Breen", /* 412 */
    (unsigned char *)"Nolan Fortin", /* 413 */
    (unsigned char *)"Peter Eldredge", /* 414 */
    (unsigned char *)"Alex Cole", /* 415 */
    (unsigned char *)"Terry DiFeliciantonio", /* 416 */
    (unsigned char *)"", /* 417 */
    (unsigned char *)"\001Associate II Software Engineers", /* 418 */
    (unsigned char *)"Andrew Burrell", /* 419 */
    (unsigned char *)"Shane Lesser", /* 420 */
    (unsigned char *)"Xavier Marshall", /* 421 */
    (unsigned char *)"", /* 422 */
    (unsigned char *)"\001Associate I Software Engineers", /* 423 */
    (unsigned char *)"Matthew Krous", /* 424 */
    (unsigned char *)"David Liu", /* 425 */
    (unsigned char *)"", /* 426 */
    (unsigned char *)"\001Associate I Tools Engineer", /* 427 */
    (unsigned char *)"Zackary Moyer", /* 428 */
    (unsigned char *)"", /* 429 */
    (unsigned char *)"\001Game Quality Assurance Assistant Manager", /* 430 */
    (unsigned char *)"Geoffrey Hills", /* 431 */
    (unsigned char *)"", /* 432 */
    (unsigned char *)"\001Game Quality Assurance Leads", /* 433 */
    (unsigned char *)"Rockie Knittel", /* 434 */
    (unsigned char *)"Jordan Barrera", /* 435 */
    (unsigned char *)"Jeremy Scheihing", /* 436 */
    (unsigned char *)"Clement Yeung", /* 437 */
    (unsigned char *)"", /* 438 */
    (unsigned char *)"\001Game Quality Assurance Testers III", /* 439 */
    (unsigned char *)"Delta Gier", /* 440 */
    (unsigned char *)"Krysta Kurata", /* 441 */
    (unsigned char *)"Cameron Abshire", /* 442 */
    (unsigned char *)"Sean Beauchene", /* 443 */
    (unsigned char *)"Scott Brunelle", /* 444 */
    (unsigned char *)"Lance Champion", /* 445 */
    (unsigned char *)"Bradley Pirkle", /* 446 */
    (unsigned char *)"Maddison Sossamon", /* 447 */
    (unsigned char *)"Mike Vinh", /* 448 */
    (unsigned char *)"Javon Skates", /* 449 */
    (unsigned char *)"Michelle Chen", /* 450 */
    (unsigned char *)"Eugene Liakhov", /* 451 */
    (unsigned char *)"Vincent Erhard", /* 452 */
    (unsigned char *)"Pavel Alexeev", /* 453 */
    (unsigned char *)"", /* 454 */
    (unsigned char *)"\001Lead Designer", /* 455 */
    (unsigned char *)"Danny Hayden", /* 456 */
    (unsigned char *)"", /* 457 */
    (unsigned char *)"\001Associate Designer", /* 458 */
    (unsigned char *)"Jess Neger", /* 459 */
    (unsigned char *)"", /* 460 */
    (unsigned char *)"\001Localization Services", /* 461 */
    (unsigned char *)"Amit Chadha", /* 462 */
    (unsigned char *)"Tushar Solanki", /* 463 */
    (unsigned char *)"Mohammad Zunaid", /* 464 */
    (unsigned char *)"Nistha Raj", /* 465 */
    (unsigned char *)"Xavier Wang", /* 466 */
    (unsigned char *)"Nept Yee", /* 467 */
    (unsigned char *)"Fabrice Maurel", /* 468 */
    (unsigned char *)"Markus Peters", /* 469 */
    (unsigned char *)"Sauro Fabi", /* 470 */
    (unsigned char *)"Fabio Massimo Caputo", /* 471 */
    (unsigned char *)"Riccardo Lausdei", /* 472 */
    (unsigned char *)"Francesca Pezzoli", /* 473 */
    (unsigned char *)"Alyona Makievskaya", /* 474 */
    (unsigned char *)"Anastasia Burina", /* 475 */
    (unsigned char *)"Artemy Nizovtsev", /* 476 */
    (unsigned char *)"Daria Zemlyakova", /* 477 */
    (unsigned char *)"Evgeniy Morozov", /* 478 */
    (unsigned char *)"Ilia Potapov", /* 479 */
    (unsigned char *)"Ivan Fedchenko", /* 480 */
    (unsigned char *)"", /* 481 */
    (unsigned char *)"\001Compatibility Services", /* 482 */
    (unsigned char *)"Pascal Faucher", /* 483 */
    (unsigned char *)"Simon Ricard", /* 484 */
    (unsigned char *)"Mathieu Pepin", /* 485 */
    (unsigned char *)"Christopher Langlois", /* 486 */
    (unsigned char *)"Charles Fontaine", /* 487 */
    (unsigned char *)"Francois Fortier", /* 488 */
    (unsigned char *)"Yanick Poirier", /* 489 */
    (unsigned char *)"", /* 490 */
    (unsigned char *)"\001Aspyr Publishing", /* 491 */
    (unsigned char *)"", /* 492 */
    (unsigned char *)"\001Director of Product", /* 493 */
    (unsigned char *)"Chris Bashaar", /* 494 */
    (unsigned char *)"", /* 495 */
    (unsigned char *)"\001Senior Manager, Business Intelligence", /* 496 */
    (unsigned char *)"Kellen Kincaid", /* 497 */
    (unsigned char *)"", /* 498 */
    (unsigned char *)"\001Senior Tableau Analyst", /* 499 */
    (unsigned char *)"Matthew Williams", /* 500 */
    (unsigned char *)"", /* 501 */
    (unsigned char *)"\001Senior Director of Business Development", /* 502 */
    (unsigned char *)"Michael Blair", /* 503 */
    (unsigned char *)"", /* 504 */
    (unsigned char *)"\001Associate Sales Director", /* 505 */
    (unsigned char *)"Anita Brey", /* 506 */
    (unsigned char *)"", /* 507 */
    (unsigned char *)"\001Sales Account Associate", /* 508 */
    (unsigned char *)"Zoe Terhune", /* 509 */
    (unsigned char *)"", /* 510 */
    (unsigned char *)"\001Product Manager", /* 511 */
    (unsigned char *)"Jordon Reese", /* 512 */
    (unsigned char *)"", /* 513 */
    (unsigned char *)"\001Associate Brand Managers", /* 514 */
    (unsigned char *)"Reid Broudy", /* 515 */
    (unsigned char *)"Matthew Ray", /* 516 */
    (unsigned char *)"", /* 517 */
    (unsigned char *)"\001Associate Market Analyst", /* 518 */
    (unsigned char *)"Joe Nixon", /* 519 */
    (unsigned char *)"", /* 520 */
    (unsigned char *)"\001Sales Support Representative", /* 521 */
    (unsigned char *)"Daniel Rodrigues", /* 522 */
    (unsigned char *)"", /* 523 */
    (unsigned char *)"\001Art Director", /* 524 */
    (unsigned char *)"Devin Cox", /* 525 */
    (unsigned char *)"", /* 526 */
    (unsigned char *)"\001Graphic Designer", /* 527 */
    (unsigned char *)"Cynthia Lopez", /* 528 */
    (unsigned char *)"", /* 529 */
    (unsigned char *)"\001Multimedia Specialist", /* 530 */
    (unsigned char *)"Sydney Mantrom", /* 531 */
    (unsigned char *)"", /* 532 */
    (unsigned char *)"", /* 533 */
    (unsigned char *)"\001General Administration", /* 534 */
    (unsigned char *)"", /* 535 */
    (unsigned char *)"\001IT Operations Manager", /* 536 */
    (unsigned char *)"John Blackburn", /* 537 */
    (unsigned char *)"", /* 538 */
    (unsigned char *)"\001Systems Administrator", /* 539 */
    (unsigned char *)"Carlos Bravo", /* 540 */
    (unsigned char *)"", /* 541 */
    (unsigned char *)"\001Help Desk Technicians II", /* 542 */
    (unsigned char *)"Tyler Kloss", /* 543 */
    (unsigned char *)"Marshall Peterson", /* 544 */
    (unsigned char *)"", /* 545 */
    (unsigned char *)"\001Senior Manager of Human Resources", /* 546 */
    (unsigned char *)"Blythe Arguez", /* 547 */
    (unsigned char *)"", /* 548 */
    (unsigned char *)"\001Office Manager", /* 549 */
    (unsigned char *)"Alexis Moyer", /* 550 */
    (unsigned char *)"", /* 551 */
    (unsigned char *)"\001Assistant Controller", /* 552 */
    (unsigned char *)"Roxie Garza", /* 553 */
    (unsigned char *)"", /* 554 */
    (unsigned char *)"\001Senior Accountant", /* 555 */
    (unsigned char *)"Kirsten Hagen", /* 556 */
    (unsigned char *)"", /* 557 */
    (unsigned char *)"\001Staff Accountant", /* 558 */
    (unsigned char *)"Brett Bingham", /* 559 */
    (unsigned char *)"", /* 560 */
    (unsigned char *)"\001Accounting Specialist", /* 561 */
    (unsigned char *)"Brooklyn Morris", /* 562 */
    (unsigned char *)"", /* 563 */
    (unsigned char *)"", /* 564 */
    (unsigned char *)"\001Special Thanks", /* 565 */
    (unsigned char *)"", /* 566 */
    (unsigned char *)"Tao Sila", /* 567 */
    (unsigned char *)"Phillip Irving", /* 568 */
    (unsigned char *)"", /* 569 */
    (unsigned char *)"\001PHL Collective", /* 570 */
    (unsigned char *)"", /* 571 */
    (unsigned char *)"\001Studio Head", /* 572 */
    (unsigned char *)"Nick Madonna", /* 573 */
    (unsigned char *)"", /* 574 */
    (unsigned char *)"", /* 575 */
    (unsigned char *)"\001Keywords Studios India", /* 576 */
    (unsigned char *)"", /* 577 */
    (unsigned char *)"\001Enyzme", /* 578 */
    (unsigned char *)"\001A Keywords Studio", /* 579 */
    (unsigned char *)"", /* 580 */
    (unsigned char *)"", /* 581 */
    (unsigned char *)"\001The Walt Disney Company", /* 582 */
    (unsigned char *)"", /* 583 */
    (unsigned char *)"\001Lucasfilm Games", /* 584 */
    (unsigned char *)"", /* 585 */
    (unsigned char *)"\001Vice President and GM of Lucasfilm Games", /* 586 */
    (unsigned char *)"Douglas Reilly", /* 587 */
    (unsigned char *)"", /* 588 */
    (unsigned char *)"\001Executive Director, Product Development", /* 589 */
    (unsigned char *)"Matthew Fillbrandt", /* 590 */
    (unsigned char *)"", /* 591 */
    (unsigned char *)"\001Executive Producer", /* 592 */
    (unsigned char *)"Orion Kellogg", /* 593 */
    (unsigned char *)"", /* 594 */
    (unsigned char *)"\001Producer II", /* 595 */
    (unsigned char *)"Michael Dailey", /* 596 */
    (unsigned char *)"", /* 597 */
    (unsigned char *)"\001Assistant Producer", /* 598 */
    (unsigned char *)"Patrick Meza", /* 599 */
    (unsigned char *)"", /* 600 */
    (unsigned char *)"\001Senior Manager, Creative Direction", /* 601 */
    (unsigned char *)"Matt Levine", /* 602 */
    (unsigned char *)"", /* 603 */
    (unsigned char *)"\001Brand Art Director", /* 604 */
    (unsigned char *)"Greg Knight", /* 605 */
    (unsigned char *)"", /* 606 */
    (unsigned char *)"\001Associate Brand Art Director", /* 607 */
    (unsigned char *)"David Yee", /* 608 */
    (unsigned char *)"", /* 609 */
    (unsigned char *)"\001Director, Marketing", /* 610 */
    (unsigned char *)"Anthony Rodriguez", /* 611 */
    (unsigned char *)"", /* 612 */
    (unsigned char *)"\001Senior Manager, Brand Marketing", /* 613 */
    (unsigned char *)"Janet Day", /* 614 */
    (unsigned char *)"", /* 615 */
    (unsigned char *)"\001Marketing Manager", /* 616 */
    (unsigned char *)"Chris Sico", /* 617 */
    (unsigned char *)"", /* 618 */
    (unsigned char *)"\001Associate Marketing Manager", /* 619 */
    (unsigned char *)"Ben Patti", /* 620 */
    (unsigned char *)"", /* 621 */
    (unsigned char *)"\001Executive Assistant", /* 622 */
    (unsigned char *)"Diana Cordio", /* 623 */
    (unsigned char *)"", /* 624 */
    (unsigned char *)"\001Disney Games Group", /* 625 */
    (unsigned char *)"", /* 626 */
    (unsigned char *)"\001Executive Vice President, Games & Digital Entertainment", /* 627 */
    (unsigned char *)"Sean Shoptaw", /* 628 */
    (unsigned char *)"", /* 629 */
    (unsigned char *)"\001Senior Vice President and Head of Disney Games Group", /* 630 */
    (unsigned char *)"Jay Ong", /* 631 */
    (unsigned char *)"", /* 632 */
    (unsigned char *)"\001Vice President, Business Development", /* 633 */
    (unsigned char *)"John Drake", /* 634 */
    (unsigned char *)"", /* 635 */
    (unsigned char *)"\001Vice President, Strategy & Business Operations", /* 636 */
    (unsigned char *)"Carrie Chen", /* 637 */
    (unsigned char *)"", /* 638 */
    (unsigned char *)"\001Vice President, Finance", /* 639 */
    (unsigned char *)"Travis Gray", /* 640 */
    (unsigned char *)"", /* 641 */
    (unsigned char *)"\001Director, Finance & Planning", /* 642 */
    (unsigned char *)"Sara Choi", /* 643 */
    (unsigned char *)"", /* 644 */
    (unsigned char *)"\001Director, Business Development", /* 645 */
    (unsigned char *)"Jamon Motes", /* 646 */
    (unsigned char *)"", /* 647 */
    (unsigned char *)"\001Business Development Manager", /* 648 */
    (unsigned char *)"Christine O'Rourke", /* 649 */
    (unsigned char *)"", /* 650 */
    (unsigned char *)"\001Technical Director", /* 651 */
    (unsigned char *)"Robert Griffis", /* 652 */
    (unsigned char *)"", /* 653 */
    (unsigned char *)"\001Senior Software Engineer", /* 654 */
    (unsigned char *)"Sean Hueber", /* 655 */
    (unsigned char *)"", /* 656 */
    (unsigned char *)"\001Disney Consumer Products, Business Affairs and Legal", /* 657 */
    (unsigned char *)"", /* 658 */
    (unsigned char *)"\001Deputy Chief Counsel", /* 659 */
    (unsigned char *)"Adam Landenberger", /* 660 */
    (unsigned char *)"", /* 661 */
    (unsigned char *)"\001Paralegal Specialist", /* 662 */
    (unsigned char *)"Kerry Hirasuna", /* 663 */
    (unsigned char *)"", /* 664 */
    (unsigned char *)"\001Executive Director, Business Affairs", /* 665 */
    (unsigned char *)"Tina Kwon", /* 666 */
    (unsigned char *)"", /* 667 */
    (unsigned char *)"\001Senior Manager, Business Affairs", /* 668 */
    (unsigned char *)"Qiana Crenshaw", /* 669 */
    (unsigned char *)"", /* 670 */
    (unsigned char *)"\001Disney Experiences, Public Relations", /* 671 */
    (unsigned char *)"", /* 672 */
    (unsigned char *)"\001Director, Communications, Games, Publishing, Merchandise, & Consumer Products", /* 673 */
    (unsigned char *)"Allison Souter", /* 674 */
    (unsigned char *)"", /* 675 */
    (unsigned char *)"\001Senior Manager, Communications", /* 676 */
    (unsigned char *)"Amanda Gonzalez", /* 677 */
    (unsigned char *)"Joe M. Sullivan", /* 678 */
    (unsigned char *)"", /* 679 */
    (unsigned char *)"\001Communications Manager", /* 680 */
    (unsigned char *)"Dylan Quintero", /* 681 */
    (unsigned char *)"", /* 682 */
    (unsigned char *)"\001Senior Specialist, Public Relations", /* 683 */
    (unsigned char *)"Melissa Lee", /* 684 */
    (unsigned char *)"", /* 685 */
    (unsigned char *)"", /* 686 */
    (unsigned char *)"\001Lucasfilm & Disney Special Thanks", /* 687 */
    (unsigned char *)"Kathleen Kennedy", /* 688 */
    (unsigned char *)"Lynwen Brennan", /* 689 */
    (unsigned char *)"Will Rosas", /* 690 */
    (unsigned char *)"Paul Southern", /* 691 */
    (unsigned char *)"Sarah Garcia", /* 692 */
    (unsigned char *)"Susan Brown", /* 693 */
    (unsigned char *)"Mario Donis", /* 694 */
    (unsigned char *)"Antonella Bonfanti", /* 695 */
    (unsigned char *)"Annie Bukowski", /* 696 */
    (unsigned char *)"Kristen Hidalgo", /* 697 */
    (unsigned char *)"Michael Kohn", /* 698 */
    (unsigned char *)"Christopher Denman", /* 699 */
    (unsigned char *)"", /* 700 */
    (unsigned char *)"", /* 701 */
    (unsigned char *)"\001Very Special Thanks", /* 702 */
    (unsigned char *)"George Lucas", /* 703 */
    (unsigned char *)"", /* 704 */
    (unsigned char *)"", /* 705 */
};
