"""Extract the four VRM sprite banks loaded by retail menu_winLoadTextures."""
from pathlib import Path
import hashlib
import struct
import sys

source = Path(sys.argv[1])
target = Path(sys.argv[2])
lines = ['/* Generated by tools/extract_menu_font_specs.py from shipped VRM data.',
         ' * Publication indices and cluts follow retail menu_winLoadTextures (CF240).']
records = []
for name, first, clut in [('winsys0', 1, 0), ('winif0', 154, 1),
                          ('winif1', 212, 2), ('winif2', 232, 3)]:
    data = (source / (name + '.vrm')).read_bytes()
    size, = struct.unpack_from('<I', data)
    assert size % 8 == 0 and size + 12 <= len(data)
    assert struct.unpack_from('<I', data, size + 8)[0] > 0
    lines.append(f' * {name}.vrm SHA256 {hashlib.sha256(data).hexdigest()}')
    for i in range(size // 8):
        page, _, y, x, h, w = struct.unpack_from('<HHBBBB', data, 4 + i * 8)
        records.append(f'    {{{first+i}, {{0x{page:04x}, {clut}, {y}, {x}, {h}, {w}}}}},')
lines += [' */', 'static const struct { unsigned index; FONTSPEC spec; }',
          'menuVrmFontSpecs[] = {', *records, '};', '']
target.write_text('\n'.join(lines), encoding='utf-8')
