#!/usr/bin/env python3
"""Extract the seven PDB-named EULA pointer tables from the matched game."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TABLES = (
    ("EULA_ENG", "JPB_EULA_ENG_LINE_COUNT", 0x4BDB60, 0x22B),
    ("EULA_GER", "JPB_EULA_GER_LINE_COUNT", 0x4BFFB0, 0x275),
    ("EULA_FRE", "JPB_EULA_FRE_LINE_COUNT", 0x4BECC0, 0x25D),
    ("EULA_ITA", "JPB_EULA_ITA_LINE_COUNT", 0x4C1360, 0x25D),
    ("EULA_SPA", "JPB_EULA_SPA_LINE_COUNT", 0x4C3AF0, 0x24E),
    ("EULA_RUS", "JPB_EULA_RUS_LINE_COUNT", 0x4C2650, 0x293),
    ("EULA_ZHO", "JPB_EULA_ZHO_LINE_COUNT", 0x4C4D60, 0x1C7),
)


def c_string(data: bytes) -> str:
    result: list[str] = []
    for value in data:
        if value == ord("\\"):
            result.append(r"\\")
        elif value == ord('"'):
            result.append(r'\"')
        elif 32 <= value < 127:
            result.append(chr(value))
        else:
            result.append(f"\\{value:03o}")
    return "".join(result)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("exe", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    image = args.exe.read_bytes()
    pe_offset = struct.unpack_from("<I", image, 0x3C)[0]
    coff = pe_offset + 4
    section_count = struct.unpack_from("<H", image, coff + 2)[0]
    optional_size = struct.unpack_from("<H", image, coff + 16)[0]
    optional = coff + 20
    image_base = struct.unpack_from("<Q", image, optional + 24)[0]
    section_table = optional + optional_size
    sections: list[tuple[int, int, int]] = []
    for index in range(section_count):
        offset = section_table + index * 40
        virtual_size, virtual_address, raw_size, raw_address = (
            struct.unpack_from("<IIII", image, offset + 8)
        )
        sections.append(
            (virtual_address, max(virtual_size, raw_size), raw_address)
        )

    def file_offset_from_rva(rva: int) -> int:
        for section_rva, section_size, raw_address in sections:
            if section_rva <= rva < section_rva + section_size:
                return raw_address + rva - section_rva
        raise ValueError(f"RVA 0x{rva:X} is outside the PE")

    def file_offset_from_va(va: int) -> int:
        return file_offset_from_rva(va - image_base)

    table_pointers: dict[str, list[int]] = {}
    pointer_order: list[int] = []
    pointer_names: dict[int, str] = {}
    pointer_data: dict[int, bytes] = {}
    for table_name, _, table_rva, count in TABLES:
        table_offset = file_offset_from_rva(table_rva)
        pointers = [
            struct.unpack_from("<Q", image, table_offset + index * 8)[0]
            for index in range(count)
        ]
        table_pointers[table_name] = pointers
        for pointer in pointers:
            if pointer in pointer_names:
                continue
            string_offset = file_offset_from_va(pointer)
            string_end = image.index(0, string_offset)
            pointer_names[pointer] = f"eula_text_{len(pointer_order):04d}"
            pointer_data[pointer] = image[string_offset:string_end]
            pointer_order.append(pointer)

    digest = hashlib.sha256(image).hexdigest().upper()
    lines = [
        "/*",
        " * Exact initialized PDB globals EULA_ENG, EULA_GER, EULA_FRE,",
        " * EULA_ITA, EULA_SPA, EULA_RUS, and EULA_ZHO, mechanically",
        " * recovered from the matched shipped executable.",
        f" * Source executable SHA-256: {digest}",
        " * Generated by tools/extract_eula_data.py.",
        " */",
        "",
        '#include "jpb/menu.h"',
        "",
    ]
    for pointer in pointer_order:
        name = pointer_names[pointer]
        value = c_string(pointer_data[pointer])
        lines.append(f'static unsigned char {name}[] = "{value}";')
    lines.append("")
    for table_name, count_name, _, _ in TABLES:
        lines.append(f"unsigned char *{table_name}[{count_name}] = {{")
        pointers = table_pointers[table_name]
        for index, pointer in enumerate(pointers):
            lines.append(
                f"    {pointer_names[pointer]}, /* {index:3d} */"
            )
        lines.extend(["};", ""])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
