#!/usr/bin/env python3
"""Extract the matched game's PDB-named ``theCredits`` pointer image.

The release PDB identifies ``theCredits`` as type 0x77D2: an array of 706
``unsigned char *`` entries at RVA 0x4C8ED0.  This small generator keeps the
otherwise hand-unfriendly initialized data reproducible without introducing a
runtime dependency on the reference executable.
"""

from __future__ import annotations

import argparse
import struct
from pathlib import Path


IMAGE_BASE = 0x140000000
THE_CREDITS_VA = 0x1404C8ED0
THE_CREDITS_COUNT = 706


def c_string(data: bytes) -> str:
    result: list[str] = []
    for value in data:
        if value == 1:
            result.append(r"\001")
        elif value == ord("\\"):
            result.append(r"\\")
        elif value == ord('"'):
            result.append(r'\"')
        elif 32 <= value < 127:
            result.append(chr(value))
        else:
            result.append(f"\\{value:03o}")
    return "".join(result)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("exe", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    image = args.exe.read_bytes()
    pe_offset = struct.unpack_from("<I", image, 0x3C)[0]
    coff = pe_offset + 4
    section_count = struct.unpack_from("<H", image, coff + 2)[0]
    optional_size = struct.unpack_from("<H", image, coff + 16)[0]
    optional = coff + 20
    image_base = struct.unpack_from("<Q", image, optional + 24)[0]
    section_table = optional + optional_size
    sections: list[tuple[int, int, int]] = []
    for index in range(section_count):
        offset = section_table + index * 40
        virtual_size, virtual_address, raw_size, raw_address = (
            struct.unpack_from("<IIII", image, offset + 8)
        )
        sections.append(
            (virtual_address, max(virtual_size, raw_size), raw_address)
        )

    def file_offset(virtual_address: int) -> int:
        rva = virtual_address - image_base
        for section_rva, section_size, raw_address in sections:
            if section_rva <= rva < section_rva + section_size:
                return raw_address + rva - section_rva
        raise ValueError(f"address 0x{virtual_address:X} is outside the PE")

    lines = [
        "/*",
        " * Exact initialized PDB global theCredits (type 0x77D2), recovered",
        " * from matched game.exe RVA 0x4C8ED0. The leading byte 1 marks a",
        " * heading; empty entries retain the original vertical spacing.",
        " * Generated by tools/extract_credit_data.py.",
        " */",
        "",
        '#include "jpb/menu.h"',
        "",
        "unsigned char *theCredits[JPB_CREDIT_LINE_COUNT] = {",
    ]
    table_offset = file_offset(THE_CREDITS_VA)
    for index in range(THE_CREDITS_COUNT):
        target = struct.unpack_from("<Q", image, table_offset + index * 8)[0]
        string_offset = file_offset(target)
        end = image.index(0, string_offset)
        escaped = c_string(image[string_offset:end])
        lines.append(f'    (unsigned char *)"{escaped}", /* {index:3d} */')
    lines.extend(["};", ""])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
